default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TaskManager_development
  username: task
  password: task
  host: localhost

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", File.basename(Rails.root)) %>_test